menu:
  Home: /
  Archives: archives
  page:
    About: about

widgets:
- tag

excerpt_link: Continue →

mathjax: true
fancybox: true

social:
  weibo: true
  twitter: true
  github: true
  gplus: true
  dribble: false
  pixiv: false
  rss: true

weibo:
  username:

twitter:
  username:

github:
  username:

gplus:
  username:

dribble:
  username:

pixiv:
  userid:

addit:
  weibo: true
  facebook: true
  twitter: true
  gplus: true
  pinit: true
  publid:
  